services:
  zero-tunnel:
    build: .
    container_name: zero-tunnel
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

  nginx-test:
    image: nginx:alpine
    container_name: nginx-test
    labels:
      zero-tunnel.enable: true
      zero-tunnel.subdomain: nginx
      zero-tunnel.port: 80
